baseUrl=https://bookstore.toolsqa.com

getBooks=/BookStore/v1/Books
getBook=/BookStore/v1/Book
addBook=/BookStore/v1/Books
updateBook=/BookStore/v1/Books/
deleteBook=/BookStore/v1/Book
deleteAllBooks=/BookStore/v1/Books